# Generated by Django 3.0.7 on 2020-07-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatdocument',
            name='name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
    ]
