# Generated by Django 3.0.7 on 2020-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_document', '0002_boatdocument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='boat_documents'),
        ),
    ]
