# Generated by Django 3.0.7 on 2020-07-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date_time', models.DateTimeField()),
                ('until_date_time', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('boat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='boat.Boat')),
            ],
        ),
    ]
