# Generated by Django 3.0.7 on 2020-07-13 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boat',
            new_name='Booking',
        ),
    ]
