# Generated by Django 3.0.7 on 2020-07-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('booking', '0002_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='event.Event'),
        ),
    ]
