# Generated by Django 3.0.7 on 2020-07-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0002_boat_title'),
        ('booking', '0002_auto_20200713_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='boat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='boat.Boat'),
        ),
    ]
