# Generated by Django 3.0.7 on 2020-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_boat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
