# Generated by Django 3.0.7 on 2020-07-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        ('booking', '0003_booking_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='transaction.Transaction'),
        ),
    ]
