# Generated by Django 3.0.7 on 2020-07-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200715_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='weekday_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='weekend_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
