# Generated by Django 3.0.7 on 2020-07-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='transaction',
        ),
    ]
