# Generated by Django 3.0.7 on 2020-07-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
