# Generated by Django 3.0.7 on 2020-07-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_transaction_membership_fee'),
        ('booking', '0012_auto_20200721_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='transaction.Transaction'),
        ),
    ]
