# Generated by Django 3.0.7 on 2020-07-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20200723_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='transaction',
        ),
    ]
