# Generated by Django 3.0.7 on 2020-07-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20200727_0920'),
        ('booking', '0015_booking_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='event.Event'),
        ),
    ]
