# Generated by Django 3.0.7 on 2020-07-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Firma', 'Firma')], default='Herr', max_length=10),
            preserve_default=False,
        ),
    ]
