# Generated by Django 3.0.7 on 2020-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200713_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
