# Generated by Django 3.0.7 on 2020-07-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200714_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='titel',
            new_name='salutation',
        ),
    ]
