# Generated by Django 3.0.7 on 2020-07-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Firma', 'Firma')], max_length=10, null=True),
        ),
    ]
