# Generated by Django 3.0.7 on 2020-07-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200713_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='licence',
            field=models.FileField(blank=True, null=True, upload_to='licences'),
        ),
    ]
