# Generated by Django 3.0.7 on 2020-07-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0001_initial'),
        ('user', '0006_auto_20200716_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_lake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_users', to='lake.Lake'),
        ),
    ]
