# Generated by Django 3.0.7 on 2020-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_favourite_lake'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_membership',
            field=models.BooleanField(default=False),
        ),
    ]
