# Generated by Django 3.0.7 on 2020-07-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_type', '0002_auto_20200721_1528'),
        ('user', '0008_user_requested_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='membership_type.MembershipType'),
        ),
    ]
