# Generated by Django 3.0.7 on 2020-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200721_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_membership',
            field=models.BooleanField(default=False),
        ),
    ]
