# Generated by Django 3.0.7 on 2020-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_type', '0002_auto_20200721_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
