# Generated by Django 3.0.7 on 2020-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooring',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='mooring',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
