# Generated by Django 3.0.7 on 2020-07-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooring', '0002_auto_20200724_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mooring',
            name='name',
        ),
        migrations.AlterField(
            model_name='mooring',
            name='address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
