# Generated by Django 3.0.7 on 2020-07-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat_model', '0002_boatmodel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatmodel',
            name='users',
        ),
    ]
