# Generated by Django 3.0.7 on 2020-07-15 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat_model', '0003_remove_boatmodel_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatmodel',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='instructed_for_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
