# Generated by Django 3.0.7 on 2020-07-14 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat_crew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatcrew',
            name='members',
            field=models.ManyToManyField(related_name='member_of_boat_crew', to=settings.AUTH_USER_MODEL),
        ),
    ]
