# Generated by Django 3.0.7 on 2020-07-14 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat_crew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatcrew',
            name='crew_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boat', to=settings.AUTH_USER_MODEL),
        ),
    ]
