# Generated by Django 3.0.7 on 2020-07-13 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat_crew', '0002_boatcrew_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatcrew',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boatcrew', to=settings.AUTH_USER_MODEL),
        ),
    ]
