# Generated by Django 3.0.7 on 2020-07-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat_crew', '0003_auto_20200714_0937'),
        ('boat_crew', '0002_boatcrew_members'),
    ]

    operations = [
    ]
