# Generated by Django 3.0.7 on 2020-07-13 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat_crew', '0003_auto_20200713_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatcrew',
            name='member',
        ),
        migrations.AddField(
            model_name='boatcrew',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='boatcrew', to=settings.AUTH_USER_MODEL),
        ),
    ]
