# Generated by Django 3.0.7 on 2020-07-13 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat_crew', '0004_auto_20200713_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatcrew',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='boatcrew', to=settings.AUTH_USER_MODEL),
        ),
    ]
