# Generated by Django 3.0.7 on 2020-07-14 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat_crew', '0004_merge_20200714_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatcrew',
            name='crew_member',
        ),
        migrations.AlterField(
            model_name='boatcrew',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of_boat_crew', to=settings.AUTH_USER_MODEL),
        ),
    ]
