# Generated by Django 3.0.7 on 2020-07-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.CharField(default='students@propulsionacademy.com', max_length=200),
        ),
    ]
