# Generated by Django 3.0.7 on 2020-07-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boat_model', '0001_initial'),
        ('boat_crew', '0001_initial'),
        ('mooring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price_weekday', models.DecimalField(decimal_places=10, max_digits=19)),
                ('price_weekend', models.DecimalField(decimal_places=10, max_digits=19)),
                ('price_full_day', models.DecimalField(decimal_places=10, max_digits=19)),
                ('description', models.CharField(max_length=600)),
                ('a_license_required', models.BooleanField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('draught', models.IntegerField()),
                ('max_crew', models.IntegerField()),
                ('recommended_crew', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boat', to='boat_crew.BoatCrew')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats', to='boat_model.BoatModel')),
                ('mooring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boat', to='mooring.Mooring')),
            ],
        ),
    ]
