# Generated by Django 3.0.7 on 2020-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='detail_description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='technical_description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
