# Generated by Django 3.0.7 on 2020-07-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0003_auto_20200715_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='price_fullday_weekday',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boat',
            name='price_fullday_weekend',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boat',
            name='price_hour_weekday',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boat',
            name='price_hour_weekend',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
