# Generated by Django 3.0.7 on 2020-07-20 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat', '0004_auto_20200715_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_boats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boat',
            name='status_sharing',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
