# Generated by Django 3.0.7 on 2020-07-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boat_crew', '0005_auto_20200714_1218'),
        ('boat', '0007_auto_20200720_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='crew',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boat', to='boat_crew.BoatCrew'),
        ),
    ]
