# Generated by Django 3.0.7 on 2020-07-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0008_auto_20200722_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='balast',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='bunks',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='cooking',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='d_license_required',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boat',
            name='engine_performance_kw',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='engine_performance_ps',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='fore_sail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='fridge',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='fuel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='gas_installation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='gennacker',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='gennacker_area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='main_sail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='motor_brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='port_220',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='roll_genua',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='sail_area',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boat',
            name='sail_freetext',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='spinacker',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='spinacker_area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='sturmsegel',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='toilet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='usb_port',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='water',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='weight',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boat',
            name='recommended_crew',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
