# Generated by Django 3.0.7 on 2020-07-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0009_auto_20200724_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='balast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='bunks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='cooking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='detail_description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='engine_performance_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='engine_performance_ps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='fore_sail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='fridge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='fuel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='gas_installation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='gennacker',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='gennacker_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='main_sail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='motor_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='port_220',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='roll_genua',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sail_freetext',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='spinacker',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='spinacker_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='sturmsegel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='technical_description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='toilet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='usb_port',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boat',
            name='water',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
