# Generated by Django 3.0.7 on 2020-07-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('document', models.ImageField(blank=True, null=True, upload_to='boat_documents')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('boat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='boat_documents', to='boat.Boat')),
            ],
        ),
    ]
