# Generated by Django 3.0.7 on 2020-07-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(blank=True, choices=[('Rechnung', 'Rechnung'), ('Eintrittsgebühr', 'Eintrittsgebühr')], max_length=20, null=True),
        ),
    ]
