# Generated by Django 3.0.7 on 2020-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('Rechnung', 'Rechnung'), ('Eintrittsgebühr', 'Eintrittsgebühr')], default='Rechnung', max_length=20),
        ),
    ]
