# Generated by Django 3.0.7 on 2020-07-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
