# Generated by Django 3.0.7 on 2020-07-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200716_0700'),
        ('transaction', '0003_auto_20200715_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='event.Event'),
        ),
    ]
