# Generated by Django 3.0.7 on 2020-07-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_booking_transaction'),
        ('transaction', '0006_remove_transaction_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='booking.Booking'),
        ),
    ]
