# Generated by Django 3.0.7 on 2020-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='membership_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
