# Generated by Django 3.0.7 on 2020-07-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_transaction_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='booking',
        ),
    ]
